name: CI

on:
  push:
    branches:
      - c4t
      - dev
  pull_request:

env:
  node_version: 18

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version: ${{ env.node_version }}
      - run: yarn install --frozen-lockfile
      - run: yarn prettier-check
      - run: yarn build
